### ISSUE TITLE
Agent don't work on builds

### ISSUE THREAD

**Issue by squalsoft** [vasiliy-briginets/teamcity-yandex-agent#1]
After creating profile agent doesn't start. How to debug this? Teamcity don't try to create instances from image in Yandex cloud.

**Comment by vasiliy-briginets** [comment]
Hello! Sorry, I missed your message. Is it still relevant? 
I can't give you advice right now, because I don't know what exactly you did.
Are you made all instructions from readme?

I tried to reproduce the problem and didn't meet any issues. 
We could try to dichotomize it.
What I did:
1) runned teamcity-server:
1a) created a new instance from "container optimize image" 
<kbd><img width="967" alt="image" src="https://user-images.githubusercontent.com/2696753/80872701-4950e500-8cbc-11ea-9a32-44cd894ee698.png"></kbd>
with simple specification:
<kbd><img width="599" alt="image" src="https://user-images.githubusercontent.com/2696753/80872720-6c7b9480-8cbc-11ea-8d5f-d072469f5948.png"></kbd>
1b) that gave me worked teamcity server (the server was running on port 8111), where I installed "teamcity-yandex-agent" 
<kbd><img width="900" alt="image" src="https://user-images.githubusercontent.com/2696753/80891282-b5871500-8ccb-11ea-8670-622d952b7c14.png"></kbd>

2) made compute image with TeamCity agent inside:
2a) created a new instance from "container optimize image" (same as in 1a) with specification:
<kbd><img width="589" alt="image" src="https://user-images.githubusercontent.com/2696753/80882894-87063b80-8cc5-11ea-946f-dab371c523b8.png"></kbd>
2b) waited until the agent tried to authorize in TeamCity server, approved this request. 
<kbd><img width="912" alt="image" src="https://user-images.githubusercontent.com/2696753/80891312-db141e80-8ccb-11ea-9a73-4895d13453c2.png"></kbd>
That gave me worked TeamCity-agent. 
2c) made compute image by cli command `yc compute image create --name teamcity-agent --source-disk-id=fhmavjrlgn4ugdpb9q01`
I found disk-id inside the output of the command `yc compute instance get agent`.
2d) deleted the instance

3) made an agent cloud profile in TeamCity server.
3a) made service account `yc iam service-account create --name teamcity-account`
3b) made IAM key `yc iam key create --service-account-name=teamcity-account -o teamcity-account.key`
3c) gave access for created service account to my folder `yc resource-manager folder add-access-binding --role editor --subject=serviceAccount:$SA_ID --id $FOLDER_ID`
3d) made cloud profile inside my TeamCity project 
<kbd><img width="1071" alt="image" src="https://user-images.githubusercontent.com/2696753/80891638-fbdd7380-8ccd-11ea-989f-a227302c4caa.png"></kbd>
Button "Add image" become available after choose  "JSON private key". I used file "teamcity-account.key" created in section 3b for that. 
I filled all necessary fields in opened form.
<kbd><img width="976" alt="image" src="https://user-images.githubusercontent.com/2696753/80891682-4e1e9480-8cce-11ea-9c61-883e0f4efd64.png"></kbd>
At the same time as I clicked "Create" TeamCity server decided to create a new instance with the name "example-agent1" in yandex cloud from my image.
3e) waited until TeamCity saw new agent. It took two or three minutes.
<kbd><img width="972" alt="image" src="https://user-images.githubusercontent.com/2696753/80891758-e3ba2400-8cce-11ea-949b-0bad33011d93.png"></kbd>



So, what do you think,  which step was the problem in your case?

p.s. I'll definitely improve instructions soon

**Comment by squalsoft** [comment]
Thank you for this great answer! I will try to do it later. Currently i created my own script which starts Yandex VM when build queue receive task and stops it after build.
